let search = document.getElementById("sbtn")
search.addEventListener("click",function(e){
    
    let first = document.getElementById("firstsearch").value
    let second = document.getElementById("secondsearch").value
    console.log(first);
    console.log(second);
    if (second=="2"){
alert("Please Scroll down for your result")
let ans = document.getElementById("output")
ans.innerHTML='<div style="background: rgb(243, 235, 235);font-size: 22px;font-weight:500;text-align: center;list-style: none;"><h2 style="margin:10px 50px;">Goa</h2><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Restaurants:</h4><ul style="list-style: none;margin: 35px auto;"><li>1.Cantare(Goan and Thai cuisine)</li><li>2.The lazy Goose(Goan seafood)</li><li>3.The Fishermans wharf</li><li>4.Pousada by the beach(Fish in banana leaf)</li><li>5.Suzies (Fine dine)</li><li>6.Olive Bar and Kitchen (Quattro-fungi Pizza)</li><li>7.Thalassa(Lamb meatballs)</li><li>8.Burger factory(Mushroom and blue cheese burger)</li><li>9.Martins Corner</li><li>10.Cavatina Cuchina Grill And Bar(Chocolate cherry tart)</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Hotels and lodge:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.Taj </li><li>2.Ibis</li><li>3.Longinhous</li><li>4.Golden tulip</li><li>5.Hyatt</li><li>6.Riva</li><li>7.Novotel</li><li>8.Marriott</li><li>9.The Leela</li><li>10.Jasmine</li><li>11.Sterling</li><li>12.Campal</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Top destinations:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.Palolem Beach(kayaking)</li><li>2.Colva Beach(Jet ski)</li><li>3.Tanshikars Working Spice Farm</li><li>4.Basilica de Bom Jesus</li><li>5.Dudhsagar Falls</li><li>6.Anjuna Market</li><li>7.Church of Our Lady of the Immaculate Conception</li><li>8.Braganza House</li><li>9.Mahadev Temple</li><li>10.Palácio do Deão(200+ year old palace)</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Emergency medical facilities:-</h4><ul style="list-style: none; padding-bottom: 20px;"><li>1.Kantak</li><li>2.Manipal</li><li>3.Nusi</li><li>4.Pai</li><li>5.Sankalp</li><li>6.Vintage</li><li>7.Vision Care</li></ul></div>'}

else if( second=="7"){
    alert("Please Scroll down for your result")
    let ans = document.getElementById("output")
    ans.innerHTML='<div style="background: rgb(243, 235, 235);font-size: 22px;font-weight:500;text-align: center;list-style: none; "><h2 style="margin:10px 50px;">Agra</h2><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Restaurants:</h4><ul style="list-style: none;margin: 35px auto;"><li>1.Dasaprakash(South Indian vegetarian cuisine)</li><li>2.Esphahan(North Indian tandoor dishes)</li><li>3.Shankar Ji(Local cuisine-dhaba,snack bar)</li><li>4.Pinch of Spice(Tandoori kebab)</li><li>5.Joneys place(Banana lassi, malai kofta)</li><li>6.Shankara Vegis(Veg thali)</li><li>7.Jahapanah(Awadhi cuisine)</li><li>8.Lashmi Villa(South Indian cuisine)</li><li>9.Stuff maker(Pancakes)</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Hotels and lodge:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.Trident </li><li>2.Taj View</li><li>3.Hotel alleviate</li><li>4.Radisson Hotel</li><li>5.Crystal Sarovar</li><li>6.Ramada Plaza</li><li>7.Joeys Hotel</li><li>8.Courtyard by Marriott</li><li>9.Double tree by Hilton</li><li>10.Howard Plaza</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Top destinations:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.Taj Mahal</li><li>2.Fatehpur Sikri</li><li>3.Agra Fort</li><li>4.Itimad-ud-daulahs Tomb</li><li>5.Mehtab Bagh</li><li>6.Akbars Tomb</li><li>7.Jama Masjid Agra</li><li>8.Chini ka Rauza</li><li>9.Dolphin Water Park</li><li>10.Anguri Bagh</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Emergency medical facilities:-</h4><ul style="list-style: none; padding-bottom: 20px;"><li>1.Pushpanjali</li><li>2.Synergy</li><li>3.Shree Krishna</li><li>4.Ram Nagu</li><li>5.Sparsh</li><li>6.Lotus super</li><li>7.Nayati</li></ul></div>'
}
else if( second=="3"){
alert("Please Scroll down for your result")
let ans = document.getElementById("output")
ans.innerHTML='<div style="background: rgb(243, 235, 235);font-size: 22px;font-weight:500;text-align: center;list-style: none;"><h2 style="margin:10px 50px;">OOTY</h2><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Top Destinations: </h4><ul style="list-style: none;margin: 35px auto;"> <li>Avalanche Lake</li><li>Ooty Lake</li><li>Emerald Lake</li><li>Ooty Botanical Gardens</li><li>Deer Park</li><li>Doddabetta Peak</li><li>Kalhatty Waterfalls</li><li>Kamraj Sagar Dam</li><li>Mudumalai National Park</li><li>Mukurthi National Park</li><<h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Hotels and lodge:-</h4><ul style="list-style: none;margin: 33px auto;"><li>Fortune Retreats Resorts - Ooty</li><li>Savoy - IHCL SeleQtions, Ooty</li><li>Accord Highland Hotel Ooty</li><li>Sterling Ooty Fern Hill</li><li>Destiny The Farmstay</li><li>Glyngarth Resorts</li><li>Meadows Residency</li><li>Fortune Resort Sullivan Court, Ooty</li><li>Sinclairs Retreat Ooty</li><li>Club Mahindra Derby Green</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Restaurants:-</h4><ul style="list-style: none;margin: 33px auto;"><li>Sidewalk Café( Popeye Pizza, Jain Pizza, Veg Lasagna) </li><li>Garden Restaurant( Dosas, idlis) </li><li>Ooty Coffee House(Filter Coffee and Ghee Roast Dosa) </li><li>Kingstar Confectionery(Traditional biscuits called Varkey) </li><li>Shinkows(Black Pepper Fry Mushrooms, American Chopsuey, Bee Hoon Noodles, Chilli Beef) </li><li>Curry and Rice(Mirchi Marie’s Mutton Makkala, Bang Bang prawns) </li><li>Quality Restaurant(Prawn Curry with Appams, Chilli Paneer, Burnt Corn Soup) </li><li>Hyderabad Biryani House(Apollo Prawns and Mutton Biryani) </li><li>Kabab Corner( Tandoori Platter) </li><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Emergency medical facilities:-</h4><ul style="list-style: none; padding-bottom: 20px;"><li>1 Govt. H.Q.Hospital, Ooty 0423 - 2442212 0423 - 2442712 </li><li>2 Govt.Sait Hospital, Ooty 0423 - 2442240 </li><li>3 Vijaya Hospital, Ooty 0423 - 2442500 0423 - 2442248 </li><li>4 Saraswathi Mani Hospital, Ooty 0423 – 2442258 0423 – 2443535 </li><li>5 Parvathi Nursing Home , Ooty 0423 - 2442145</li> <li>6 Sanhita Hospital, Ooty 0423 - 2443671</li> <li>7 Nirmala Nursing Home, Ooty 0423 - 2442215</li> <li>8 Blisy Eye Hospital, Ooty 0423 - 2441011</li> <li>9 District TB.Centre, Ooty 0423 - 2446951 10 ESI Dispensary , Ooty</li></ul></div>'}

else if( second=="8"){
    alert("Please Scroll down for your result")
    let ans = document.getElementById("output")
    ans.innerHTML='<div style="background: rgb(243, 235, 235);font-size: 22px;font-weight:500;text-align: center;list-style: none;"><h2 style="margin:10px 50px;">Amritsar:</h2><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Top Destinations: </h4><ul style="list-style: none;margin: 35px auto;"><li>The Golden Temple</li><li>Wagah Border Ceremony</li><li>Partition Museum</li><li>Mandir Mata Lal Devi</li><li>Jallianwala Bagh</li><li>Baba Atal Tower</li><li>Ram Bagh Gardens</li><li>Shri Durgiana Mandir</li><li>Gobindgarh Fort</li> <li>Hall Bazaar</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Hotels and lodge:-</h4><ul style="list-style: none;margin: 33px auto;"><li>Holiday Inn Amritsar Ranjit Avenue</li><li>Lemon Tree Hotel, Amritsar</li><li>Fairfield by Marriott Amritsar</li><li>Hyatt Regency Amritsar</li><li>Ramada by Wyndham Amritsar</li><li>Golden Sarovar Portico</li><li>Hotel Sawera Grand</li><li>Hotel PR Residency</li><li>Hotel Hong Kong Inn</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Restaurants:-</h4><ul style="list-style: none;margin: 33px auto;"><li>Bharawan Da Dhaba</li><li>Kanha Sweets</li><li>All India Famous Kulcha</li><li>The Kulcha Land</li><li>Brothers Dhaba</li><li>Kesar Da Dhaba</li><li>Makhan Fish & Chicken Corner</li><li>Crystal Restaurant</li><li>Adarsh Meat Shop</li><li>Bittu Meat Wala</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Emergency medical facilities:-</h4><ul style="list-style: none; padding-bottom: 20px;"><li>K D Hospital</li><li>Altec Laser And Superspeciality Hospital, Amritsar</li><li>Jai Kamal Eye Hospital</li><li>Ranjit Hospital</li><li>Nayyar Hospital</li><li>Mahajan Hospital</li><li>Sanjeevan Hospital</li><li>Smt. Paarvati Devi Hospital</li><li>Chikitsa Eye And Ent Hospital</li><li>Emc Superspeciality Hospital - (Unit Iii) Green Avenue</li></ul></div>'
}

else if( second=="4"){
    alert("Please Scroll down for your result")
    let ans = document.getElementById("output")
ans.innerHTML='<div style="background: rgb(243, 235, 235);font-size: 22px;font-weight:500;text-align: center;list-style: none;"><h2 style="margin:10px 50px;">Manali</h2><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Restaurants:</h4><ul style="list-style: none;margin: 35px auto;"><li>1.Mount View Restaurant</li><li>2.The Open air and multi-cuisine</li><li>3.Basil leaf restaurant</li><li>4.La Plage</li><li>5.11 Forno</li><li>6.Cafe 1947</li><li>7.Chopsticles Restaurants</li><li>8.Driftes Cafe</li><li>9.Johnsons Cafe</li><li>10.Fat plate restaurant</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Hotels and lodge:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.RigZin Nest cottages </li><li>2.Holiday heights and spa</li><li>3.Hotel river bank and restaurant</li><li>4.Sylvan Hues Manali</li><li>5.Village House Manali</li><li>6.Hotel Highway Inn</li><li>7.The holiday resort cottages and spa</li><li>8.ManuAllaya Resort and Spa</li><li>9.Snow Peak Retreat and cottages Manali</li><li>10.The Orchid Greens Resort</li><li>11.Kalista Resort</li><li>12.Apple Country Resorts</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Top destinations:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.Hadimba Devi Temple</li><li>2.Jogini Falls</li><li>3.The Manali Gompa</li><li>4.Hampta Pass</li><li>5.Arjun Gufa</li><li>6.Solang Valley</li><li>7.Van Vihar</li><li>8.Rahala Falls</li><li>9.Rohtang Pass</li><li>10.Vashisht Hot water springs</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Emergency medical facilities:-</h4><ul style="list-style: none; padding-bottom: 20px;"><li>1.Bhanoo Hospital</li><li>2.Manu Diagnostic Centre and Hospital</li><li>3.Rawat Clinic</li><li>4.Civil Hospital</li><li>5.Kullu Valley Hospital</li><li>6.Mannat Ayurvedic Clinic</li><li>7.JAI Prakash Hospital</li></ul></div>'}


else if( second=="9"){
    alert("Please Scroll down for your result")
    let ans = document.getElementById("output")
ans.innerHTML='<div style="background: rgb(243, 235, 235);font-size: 22px;font-weight:500;text-align: center;list-style: none;"><h2 style="margin:10px 50px;">Kutch</h2><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Restaurants:</h4><ul style="list-style: none;margin: 35px auto;"><li>1.Sankalp(Masala Dosa)</li><li>2.Comfort INN Prince(Thali)</li><li>3.Zorba the Buddha(Gujrati Thali)</li><li>4.Green Rock</li><li>5.Noorani Restaurant(Mutton Curry)</li><li>6.Bin Hariff(Dabeli)</li><li>7.Sabri Fast food(Punjabi,South Indian cuisine)</li><li>8.Neelam Restaurant(South and North Indian cuisine)</li><li>9.Annapurna Restaurant(Khichadi Kadhi)</li><li>10.Marina Restaurant(Hyderabadi Biryani)</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Hotels and lodge:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.Hotel Kalash Mandvi </li><li>2.The Fern Royal Form resort</li><li>3.Hill View Resort</li><li>4.Rann Resort Dholavira</li><li>5.Ramada by Wyndham</li><li>6.Seven Sky Clarks Exotica</li><li>7.The Neemaya Hotel</li><li>8.The Fern residency Mundra</li><li>9.Hotel Zorba</li><li>10.Kutch Birding lodge</li><li>11.Hotel Kutch desert</li><li>12.Serena Beach resort</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Top destinations:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.Rann Of Kutch</li><li>2.Bhuj</li><li>3.Dholavira</li><li>4.Gandhidham</li><li>5.Mandvi</li><li>6.Kandla</li><li>7.Narayan Sarovar</li><li>8.Lakhpat</li><li>9.Hodka</li><li>10.Nakhatrana</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Emergency medical facilities:-</h4><ul style="list-style: none; padding-bottom: 20px;"><li>1.Kutch healthcare</li><li>2.Massom Child care Hospital</li><li>3.Referral Hospital</li><li>4.Kutch Lifecare</li><li>5.Nanvaty Hospital</li><li>6.Medicare Clinic</li><li>7.Bhojay Sarvoday trust hospital</li></ul></div>'}


else if( second=="6"){
    alert("Please Scroll down for your result")
    let ans = document.getElementById("output")
ans.innerHTML='<div style="background: rgb(243, 235, 235);font-size: 22px;font-weight:500text-align: center;list-style: none;"><h2 style="margin:10px 50px;">Gulmarg</h2><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Top Destinations:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1. Apharwat Peak</li> <li>2. Alphater lake</li><li>3. Gulmarg Gondola</li> <li>4. Baba Reshi Shrine</li><li>5. Outer Circle Walk</li><li>6. Ningle Nallah</li><li>7. Drang </li><li>8. Kongdori</li><li>9. Rani Temple</li><li>10. St. Marry’s Church</li><li>11. Gulmarg Biosphere Reserve </li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Restaurants:</h4><ul style="list-style: none;margin: 35px auto;"><li>1. Bakshi (Rogan Josh & Dam Aloo)</li><li>2. Ahdoos Hotel (Modur Palace)</li><li>3. Pine View Restaurant (Nadru Monje(fries)/ Yakhni)</li><li>4. Café Samovar (Shir Chai/Noon Chai & Sheermal )</li><li>5. Black Bear Brew (Coffee & Tea)</li><li>6. Igloo Café (Kahwa(green tea))</li><li>7. Nedous Dining Room (Kashmiri Wazwan)</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Hotels and lodge:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.The Vintage Gulmarg </li><li>2.Shaw Inn</li><li>3.Royal Park Hotel</li><li>4.The Rosewood</li><li>5.Nedou’s Hotel</li><li>6.Gulmarg Meadows</li><li>7.Pine View Resort</li><li>8.Kolahoi Green Heights Gulmarg</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Emergency medical facilities:-</h4> <ul style="list-style: none; padding-bottom: 20px; "><li>1. Gulmarg Primary Health Centre</li><li>2. Mahajan Clinic </li><li>3. Khalid Medicate </li><li>4. Dr. Lal Pathlabs </li></ul> </div>'}

else if( second=="11"){
    alert("Please Scroll down for your result")
    let ans = document.getElementById("output")
ans.innerHTML='<div style="background: rgb(243, 235, 235);font-size: 22px;font-weight:500;text-align: center;list-style: none;"><h2 style="margin:10px 50px;">Andaman</h2><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Restaurants:</h4><ul style="list-style: none;margin: 35px auto;"><li>1.Full Moon Cafe(Seafood)</li><li>2.Annapurna Restaurant(Vegetarian Delight)</li><li>3.New Lighthouse Restaurant(Asian)</li><li>4.The Bayview at Sinclairs(Diverse cuisine)</li><li>5.Bonova Cafe and pub(Thai and continental)</li><li>6.Anju Coco(Grilled Tuna delicacy)</li><li>7.Fat Martins(South Indian Cuisine)</li><li>8.Bayview(Seafood)</li><li>9.Mandalay(Indian,Asian and Chinese)</li><li>10.Red Snapper(Fish)</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Hotels and lodge:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.Mahira Residency </li><li>2.Hotel The North Reef</li><li>3.Taj Exotica resort and spa</li><li>4.Seashell Port Blair</li><li>5.Coral Reef hotel</li><li>6.Sincails bayview</li><li>7.Havelock country homes</li><li>8.The Aura resort</li><li>9.Ocean Tree beach resort and spa</li><li>10.Comfort Inn Blue Waves</li><li>11.Hotel value stay</li><li>12.Aqua horizon</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Top destinations:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1.Port Blair</li><li>2.Swaraj Dweep</li><li>3.Nicobar Islands</li><li>4.Baratang</li><li>5.Neil Island</li><li>6.Little Andaman</li><li>7.Mahatma Gandhi marine national park</li><li>8.Barren Island</li><li>9.Diglipur</li><li>10.Cinque Island</li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Emergency medical facilities:-</h4><ul style="list-style: none; padding-bottom: 20px;"><li>1.INHS Dhanvantari hospital</li><li>2.Vidyadeep hospital</li><li>3.Pillar hospital</li><li>4.RP Port Blair</li><li>5.Government hospital Bambooflat</li><li>6.Primary health centre</li><li>7.BJR Hospital</li></ul></div>'}

else if( second=="1"){
    alert("Please Scroll down for your result")
    let ans = document.getElementById("output")
ans.innerHTML='<div style="background: rgb(243, 235, 235);font-size: 22px;font-weight:500; text-align: center;list-style: none;"><h2 style="margin:10px 50px;">Mysore</h2><h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Top Destinations:-</h4><ul style="list-style: none;margin: 33px auto;"><li>1. Mysore Palace</li><li>2. Karanji Lake</li><li>3. Chamundeshwari Temple</li><li>4. Jaganmohan Palace </li><li>5. Mysore Zoo </li><li>6. Jayalakshmi Vilas</li><li>7. Shuka Vana </li><li>8. C V Rangacharlu Memorial Hall</li><li>9. Lalitha Mahal </li><li>10. Trinesvaraswamy Temple</li> </ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Restaurants:</h4><ul style="list-style: none;margin: 35px auto;"><li>1. Tiger Trail (Succulent Kebab)</li><li>2. Oyster Bay(Kung Pao)</li><li>3. Vinayak Mylari (Dosa)</li><li>4. Hotel RRR (Grilled Mutton  and Fish)</li><li>5. Anima Madhva Bhavan(Tradional Vegetarian and Vegan Dishes ) </li><li>6. Green Leaf(Gojju & Tovve)</li><li>7. Kapoor’s café (Thatte Idli & Uppittu)</li> <li>8. Highway 18(Raggi Muddae)</li><li>9. Amrutha (Vada Sambar and Kesari Bath ) </li> <li>10. Polar Bear(Chiroti-Pastry & Obbattu) </li></ul> <h4 style="font-weight: bold;border-bottom: 2px solid black; padding-bottom: 5px;">Hotels and lodge:-</h4> <ul style="list-style: none;margin: 33px auto;"><li>1. Grand Mercure Mysore </li><li>2. Radisson Blu Plaza Hotel Mysore </li><li>3. Hotel MB International Palace Side</li><li>4. Ni Ambaari Suites in Mysore </li><li>5. REGALIA INN & SUITES </li><li>6. Fortune JP Palace</li><li>7. Royal Orchid Metropole Mysore</li> <li>8. Le Oak Inn</li><li>9. Rio Meridian Hotel</li><li>10. K F International</li><li>11. The Atrium Boutique Hotel </li></ul><h4 style="font-weight: bold;border-bottom: 2px solid black;padding-bottom: 5px;">Emergency medical facilities:-</h4><ul style="list-style: none; padding-bottom: 20px;"><li>1. Soukya Health Care & Panchakarma Centre </li><li>2. Nisarga Health Care Centre</li><li>3. Apollo BGS Hospital </li><li>4. JSS Hospital</li><li>5. K R Hospital</li><li>6. Dhanvantri Health care</li><li>7. Columbia Asia Hospital</li></ul></div>'}

})
